# Generated by Django 4.0.2 on 2022-02-05 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
